function [ lambda, wald_stat, p_val, mse, log_like, n_snps_chosen ] = ...
    fast_lmm_autoselect( X, X_test, y, covar, cutoffs, worker_id )

base_filename = sprintf('geno_autoselect%d', worker_id);

write_to_t_file(sprintf('../data/%s', base_filename), ...
    X, X_test, y, covar);

% Write cutoffs to file
f = fopen(sprintf('../data/%s_ASvalues.txt', base_filename), 'w');
fprintf(f, '%d\t', cutoffs);
fclose(f);

% Run FastLMM autoselect
cmd = sprintf(['../FaSTLMM.204.Linux/Linux_MKL/fastlmmc ', ...
            '-autoSelect ../data/%s ', ...
            '-autoSelectSearchValues ../data/%s_ASvalues.txt ', ...
            '-randomSeed 1 ', ...
            '-autoSelectFolds 10 ', ...
            '-tfileSim ../data/%s_cov ', ...
            '-pheno ../data/%s_pheno.txt ', ...
            '-mpheno 1 ', ...
            '-covar ../data/%s_covar.txt'], ...
            base_filename, base_filename, base_filename, base_filename, base_filename);
        
system(cmd);

% Run FastLMM on the extracted SNPs
cmd = sprintf(['../FaSTLMM.204.Linux/Linux_MKL/fastlmmc ', ...
            '-out ../data/%s.out.txt ', ...
            '-tfile ../data/%s_test ', ...
            '-tfileSim ../data/%s_cov ', ...
            '-extractSim ../data/%s.snps.txt ', ...
            '-pheno ../data/%s_pheno.txt ', ...
            '-mpheno 1 ', ...
            '-covar ../data/%s_covar.txt'], ...
            base_filename, base_filename, base_filename, base_filename, base_filename, base_filename);

system(cmd);

% Process output
output = importdata(sprintf('../data/%s.out.txt', base_filename));

% Reorder the output by the actual SNP ordering
[~, I] = sort(output.data(:, 1));

wald_stat = output.data(I, 12);
p_val = output.data(I, 5);
lambda = lambda_GC(wald_stat);

% Read number of SNPs that were chosen by autoselect
output = importdata(sprintf('../data/%s.xval.txt', base_filename));
mse = output.data(:, 2);
log_like = output.data(:, 3);

[~, I] = max(log_like);
n_snps_chosen = cutoffs(I);

end
